apiVersion: v1
kind: Service
metadata:
  name: belajar-nodejs-service
  namespace: belajar-nodejs
spec:
  selector:
    app: belajar-nodejs-dasar
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
