{{- if .Values.mongodb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "belajar-nodejs-dasar.fullname" . }}-mongodb
  labels:
    {{- include "belajar-nodejs-dasar.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "belajar-nodejs-dasar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "belajar-nodejs-dasar.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.mongodb.database }}"
            {{- if .Values.mongodb.auth.enabled }}
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "{{ .Values.mongodb.auth.rootUser }}"
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "belajar-nodejs-dasar.fullname" . }}-mongodb
                  key: mongodb-root-password
            {{- end }}
          {{- with .Values.mongodb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      {{- with .Values.mongodb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mongodb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: mongodb-data
        {{- if .Values.mongodb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.persistence.existingClaim | default (printf "%s-mongodb" (include "belajar-nodejs-dasar.fullname" .)) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
{{- end }}