{{- if .Values.mongodb.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "belajar-nodejs-dasar.fullname" . }}-mongodb
  labels:
    {{- include "belajar-nodejs-dasar.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size | default "8Gi" }}
{{- end }}