{{- if .Values.mongodb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "belajar-nodejs-dasar.fullname" . }}-mongodb
  labels:
    {{- include "belajar-nodejs-dasar.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "belajar-nodejs-dasar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
{{- end }}